### ISSUE TITLE
Depending on a release of a sub-project confuses the SBT plugin

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#117]
Happens with the `readme` module of Ammonite: it transitively depends on `com.lihaoyi:ammonite-ops_2.11`, but does not depend on the sub-project that builds it. It only depends on a released version of it. But the `InterProjectRepository` of the SBT plugin is too naive, and confuses one for the other.

I have no idea of the amount of effort required to get a better view of inter-project dependencies from SBT.

**Comment by nafg** [comment]
Why does readme do that?

**Comment by alexarchambault** [comment]
The `readme` sub-project depends on `com.lihaoyi:ammonite-ops_2.11:0.4.8` via `com.lihaoyi:scalatex-site_2.11:0.3.5`. The coursier SBT plugin thinks this is a dependency towards the `ops` sub-project (that builds `com.lihaoyi:ammonite-ops_2.11`), thus puts nothing in the classpath for this particular module (SBT is supposed to put other sub-project classpaths in dependees itself). But SBT sees no `dependsOn(ops)` on `readme`, thus puts nothing in the classpath either. So `ammonite-ops` ends up missing in the classpath...

**Comment by alexarchambault** [comment]
Fixed at least since `1.0.0-M14`.
