### ISSUE TITLE
SHA1 sums with too much junk not handled fine

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#131]
Occurs for `org.apache.spark:spark-sql_2.11:1.2.0` from Central... but not with the one from JCenter!

junk:
```
$ curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom.sha1
./spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom:
EBCE 8C6D 3CEB 5C55 B257  EFF0 14F4 BA13 AEB4 BAE7
```

no junk:
```
$ curl https://jcenter.bintray.com/org/apache/spark/spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom.sha1
ebce8c6d3ceb5c55b257eff014f4ba13aeb4bae7
```

**Comment by darkjh** [comment]
Do we have just these 2 versions of `sha1` out there, or it's just Central's fault?
Seems we need to add some check & conversion code in `validateChecksum` method.

**Comment by alexarchambault** [comment]
`org.apache.spark:spark-sql_2.11:1.2.0` from Central is the only checksum I know that confuses coursier... Other artifacts (other versions of this one, or other modules), or this one but from JCenter, are fine afaict.

Checksum values are extracted from the content of the checksum files around [these lines](https://github.com/alexarchambault/coursier/blob/59c24ed258896e7d7a3ebd3db389ed15f933234b/cache/src/main/scala/coursier/Cache.scala#L360-L365).

I couldn't find any reference about the format of checksum files... These are just parsed heuristically. We should try to have the parser be fine with `https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom.sha1` too.
