### ISSUE TITLE
sbt.override.build.repos not honored

### ISSUE THREAD

**Issue by kralikba** [alexarchambault/coursier#134]
I am using a local maven proxy for my sbt builds.
In order to make sure that everything is fetched through this proxy, I have set `-Dsbt.override.build.repos=true`.
This should cause sbt builds to not use any other repositories than those specified in `~/.sbt/repositories`.
In spite of this, Coursier connects to other repositories specified by additional resolvers in the various projects' build definitions.

**Comment by alexarchambault** [comment]
No efforts were made in the SBT plugin to support `sbt.override.build.repos`, looks like it's not automatic. The plugin just follows what's in `externalResolvers`. That should definitely be addressed.
