### ISSUE TITLE
java 6 support

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#137]
a lot of projects (including ensime-serever) use java 6 because its the lowest common denominator and **still** the official JDK for stable releases of scala.

But using your sbt plugin on a java 6 project gives

```
[error] java.lang.UnsupportedClassVersionError: coursier/CoursierPlugin$ : Unsupported major.minor version 51.0
```

**Comment by alexarchambault** [comment]
Should be fixed on the [topic/java-6](https://github.com/alexarchambault/coursier/tree/topic/java-6) branch.

**Comment by alexarchambault** [comment]
Use the Java 6 specific SBT plugin with
```scala
addSbtPlugin("com.github.alexarchambault" % "coursier-sbt-plugin-java-6" % "1.0.0-M8")
```

**Comment by fommil** [comment]
You're the best :smile:

**Comment by alexarchambault** [comment]
Considering this fixed by the [`topic/java-6`](https://github.com/alexarchambault/coursier/tree/topic/java-6) branch. I'm intending to regularly merge it with master until 1.0 final.
