### ISSUE TITLE
Keep track of missing sources / javadoc in cache...

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#138]
...in the less risky cases.

E.g. for non changing (=non snapshots) artifacts, if a metadata file is found, and we get exactly a 404 HTTP error for an artifact, I think we can safely assume that the corresponding file won't magically appear later, and keep track of it missing. So that we won't try to get it and fail again the next times.

That should make `updateClassifier` faster in some SBT projects (ensime-server in particular).

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/commit/1731fca26ccb2e716970c1c45bb110a58cd2b785.

**Comment by fommil** [comment]
is this in M10 ?

**Comment by alexarchambault** [comment]
@fommil It should be. `updateClassifiers` now taking 5~6 seconds on my machine (so it itself says).
