### ISSUE TITLE
coursier SBT plugin breaking `console` command in 2.10

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#143]
Happens with shapeless for example...

It seems that some JLine dependency is missing somewhere...

The console is not fully broken, one can still type things, but in a much less user-friendly way.

**Comment by alexarchambault** [comment]
I can't find jline in `allDependencies`, which is used to get dependencies. It possibly has to be added manually.

**Comment by velvia** [comment]
I can still use jline (up arrow works for example)

**Comment by alexarchambault** [comment]
Seems fixed (`sbt ++2.10.6 console` is fine with shapeless, with sbt-coursier `1.0.0-M15-1`).
