### ISSUE TITLE
Repository URL resolution issue

### ISSUE THREAD

**Issue by nemo83** [alexarchambault/coursier#146]
Hi,

I've noticed of a possible issue when building the URL for resources against our nexus repo.

The repo is configured in the `~/.sbt/repositories` as follows:

`internal-releases: https://nexus.*company_name*.com/nexus/content/repositories/internal-releases/, [organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/ivy-[revision].xml, [organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[artifact]-[revision](-[classifier]).[ext], mavenCompatible`

The artifact to be resolved is 

* com.company_name
* zk-config
* 0.1.2

The URL that is build in order to resolve the artifact is:
`https://nexus.company_name.com/nexus/content/repositories/internal-releases/com.company_name/zk-config/0.1.2/ivy-0.1.2.xml`

while if we replace the . (dot) between *com* and *company_name* (eg.:

`https://nexus.company_name.com/nexus/content/repositories/internal-releases/com/company_name/zk-config/0.1.2/ivy-0.1.2.xml`)

everything works fine. Can you please take a look or point me in the right direction so that I can fix this myself and submit a PR ?

Thanks!

P.S. Congrats for library and pressie done in Poland!! :100:

**Comment by alexarchambault** [comment]
Hey!

Does it work as is with SBT (without the coursier SBT plugin)?

The Ivy support in coursier uses the same tokens as in the [Ivy documentation](http://ant.apache.org/ivy/history/2.4.0/concept.html#patterns). According to it, `[organisation]` should indeed be `com.my_company`. For `com/my_company`, `[orgPath]` should be used instead.

Maybe SBT follows only the `mavenCompatible` flag, and ignores the pattern. (That should be checked.) In this case, the coursier SBT plugin should do it too then (and a PR for that would be welcome :-).

**Comment by nemo83** [comment]
It does. and indeed if I switch to orgPath works.
I have a different issue now. Will investigate further and update this thread. thank for the quick reply...
