### ISSUE TITLE
Support for SBT credentials

### ISSUE THREAD

**Issue by patrick-bohan** [alexarchambault/coursier#147]
Docs http://www.scala-sbt.org/0.13/docs/Publishing.html#Credentials

We use a private Artifactory setup with credentials, and it appears that coursier does not respect that setting. We use the form ```credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")``` if that matters.

**Comment by alexarchambault** [comment]
@patrick-bohan What do you mean? These are not supposed to be used to fetch dependencies. Only to publish some, which the coursier SBT plugin doesn't do (apart for the small interaction between the `update` and `publish` commands that it has to handle).

**Comment by patrick-bohan** [comment]
I think there is some documentation misinformation in SBT: while under the "Publishing" setting the credentials are indeed use for fetching as well as publishing. I can verify by commenting out the credentials line in my own SBT project. When I do that fetching to start failing. I think this is a case of "the code is truth".

**Comment by alexarchambault** [comment]
Ah ok. Looks like just basic HTTP authentication, support for that could be added. Special care should be taken, so that the cache of a given repo, with different authentications or no authentication, would be kept separate.

**Comment by patrick-bohan** [comment]
LGTM

**Comment by alexarchambault** [comment]
PRs welcome :-)

**Comment by vito-c** [comment]
+1

**Comment by yeghishe** [comment]
+1

**Comment by melrief** [comment]
+1

**Comment by jlandahl** [comment]
+1

Very much need this for accessing private repositories.

**Comment by alexarchambault** [comment]
Fixed since https://github.com/alexarchambault/coursier/issues/243 (included in `1.0.0-M12`). https://github.com/alexarchambault/coursier/pull/257 is about to make it compatible with the `credentials` key from SBT (will be included in `1.0.0-M12-1` to come).
