### ISSUE TITLE
Scala 2.12.0-M3 support

### ISSUE THREAD

**Issue by guersam** [alexarchambault/coursier#150]
I've put coursier-sbt-plugin into my global sbt setting so that it fails when I run cross-building with Scala 2.12.0-M3. I'm willing to open a PR which enables Scala 2.12.0-M3 cross build and bumps Scalaz to 7.2.0, which breaks the binary and (probably) source compatibility.

**Comment by guersam** [comment]
Oops, the reason of failure was something else, now it works just fine without Scala 2.12 version now.  I also noticed that there are many dependencies which don't support Scala 2.12 yet. Sorry for the noise, I'll just open a PR bumping some dependencies such as Scalaz.

**Comment by alexarchambault** [comment]
Realizing I forgot drop you a word.

I'd be fine with cross-building for 2.12, although I haven't given that a try yet, so, yeah, some dependencies may not support it yet.

About scalaz 7.2, I was thinking about switching to it post-1.0, unless there are particularly compelling arguments to switch it. Ultimately, I'd like to switch to cats, once it has a substitute for `scalaz.concurrent.Task`.

**Comment by guersam** [comment]
Agreed, also found out Scalaz 7.2 is not released for Scala 2.10 + Scala.js. +1 on switching to cats as well.
