### ISSUE TITLE
update-chaging mode updating too many things

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#154]
E.g.
```
SCALA_VERSION=${SCALA_VERSION:-2.11.7}

./coursier-java-6 \
  fetch \
  -r ivy2Cache \
  -r http://bits.netbeans.org/nexus/content/groups/netbeans \
  -r https://oss.sonatype.org/content/repositories/snapshots \
  org.ensime:ensime_2.11:0.9.10-SNAPSHOT \
  -V org.scala-lang:scala-compiler:$SCALA_VERSION \
  -V org.scala-lang:scala-library:$SCALA_VERSION \
  -V org.scala-lang:scala-reflect:$SCALA_VERSION \
  -V org.scala-lang:scalap:$SCALA_VERSION \
  -m update-changing
```
which tries to update netbeans / `RELEASE???` dependencies, whereas it shouldn't.

**Comment by hedefalk** [comment]
I'm using Coursier now to bootstrap ensime-atom. Love it, thanks a lot!

Just want to report that with local cache filled, `-m update-changing` gives me 29 seconds. Without it is 2 seconds so a pretty significant difference for the end user.

`/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -noverify -jar coursier resolve -r file:///$HOME/.m2/repository -r https://oss.sonatype.org/content/repositories/snapshots -r https://jcenter.bintray.com/ org.ensime:ensime_2.11:0.9.10-SNAPSHOT -V org.scala-lang:scala-compiler:2.11.7 -V org.scala-lang:scala-library:2.11.7 -V org.scala-lang:scala-reflect:2.11.7 -V org.scala-lang:scalap:2.11.7`

What do you think I can expect when this issues is taken care of?

I'm thinking, if this can be really fast here I would like to remove the entire classpath-writeout-to-file that ensime-atom does (ensime-* does it too) and just always resolve in-mem. ping @fommil.

**Comment by hedefalk** [comment]
```
rm -rf $HOME/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime && /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -noverify -jar coursier resolve -r file:///$HOME/.m2/repository -r https://oss.sonatype.org/content/repositories/snapshots -r https://jcenter.bintray.com/ org.ensime:ensime_2.11:0.9.10-SNAPSHOT -V org.scala-lang:scala-compiler:2.11.7 -V org.scala-lang:scala-library:2.11.7 -V org.scala-lang:scala-reflect:2.11.7 -V org.scala-lang:scalap:2.11.7
```
is 6 sec on my machine…

**Comment by alexarchambault** [comment]
`update-changing` should work since https://github.com/alexarchambault/coursier/pull/190. For reasons that are still unclear to me, it still tries to get things corresponding to versions like `RELEASE731` in `update-changing` mode though.
