### ISSUE TITLE
spurious(?) /dev/tty error

### ISSUE THREAD

**Issue by pfn** [alexarchambault/coursier#166]
`bash: /dev/tty: No such device or address`

this error pops up when running via idea-sbt-plugin in IntelliJ on Windows

**Comment by alexarchambault** [comment]
It originates from https://github.com/lihaoyi/Ammonite/blob/18fbbe05d80220541c3dccc14c08a2f424d9c775/terminal/src/main/scala/ammonite/terminal/Utils.scala#L71... A fix could be sent to Ammonite, or this function could be re-implemented more silently here.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/pull/201.
