### ISSUE TITLE
ModuleID.from(URL) is not honored

### ISSUE THREAD

**Issue by pfn** [alexarchambault/coursier#196]
I have to consume an artifact that is published naked (no ivy or pom xml descriptors). SBT supports this natively by doing something like

`libraryDependencies += group % art % ver from aURL`

coursier is ignoring this and failing :(

**Comment by alexarchambault** [comment]
Not supported for now indeed. Shouldn't be too hard to add though.

**Comment by pfn** [comment]
Will you be adding it soon? It's preventing me from setting coursier up as
a global plugin, and I can't be bothered to add it to projects individually
(way too many projects)

**Comment by alexarchambault** [comment]
Next milestone if this works straightaway. Next week I think.

**Comment by alexarchambault** [comment]
`1.0.0-M10` was published earlier than expected, that should be for the next milestone.

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/alexarchambault/coursier/issues/212.
