### ISSUE TITLE
missing scala-library on windows

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#208]
in this build https://ci.appveyor.com/project/fommil/ensime-server-circ6/build/1.0.82 for our PR into ensime-server, something bad happened. Windows specific?

Feel free to raise a PR against ensime-server to use our CI and get a reproduction, or I can get you a Windows 7 virtualbox image if that would help.

**Comment by alexarchambault** [comment]
Should be fixed since https://github.com/alexarchambault/coursier/issues/223 in particular.
