### ISSUE TITLE
fails to resolve the scripted plugin

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#236]
The `scripted` plugin can be enabled by adding this to `project/plugins.sbt`

```
libraryDependencies += "org.scala-sbt" % "scripted-plugin" % sbtVersion.value
```

but with coursier enabled, it leads to this:

```
[error] 
[error] 2 error(s):
[error]   org.scala-sbt:sbt-launch:0.13.11:
[error]     /home/fommil/.sbt/0.13/plugins/target/resolution-cache/org.scala-sbt/sbt-launch/0.13.11/resolved.xml.xml
[error]     Not found
[error]     /home/fommil/.ivy2/local/org.scala-sbt/sbt-launch/0.13.11/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/0.13.11/sbt-launch-0.13.11.pom
[error]   org.scala-sbt:scripted-sbt:0.13.11:
[error]     /home/fommil/.sbt/0.13/plugins/target/resolution-cache/org.scala-sbt/scripted-sbt/0.13.11/resolved.xml.xml
[error]     Not found
[error]     /home/fommil/.ivy2/local/org.scala-sbt/scripted-sbt/0.13.11/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt/0.13.11/scripted-sbt-0.13.11.pom
java.lang.Exception: Encountered 2 error(s) in dependency resolution
```

looks like maybe the maven / ivy / sbt-plugin-weirdness naming conventions are not in alignment? (or maybe a default repo is missing for sbt plugins)

**Comment by fommil** [comment]
looks like this is an issue with sbt, workaround is to add

```
resolvers += Resolver.typesafeIvyRepo("releases")
```

**Comment by alexarchambault** [comment]
@fommil Strange that you have to manually add it. coursier itself uses scripted [this way](https://github.com/alexarchambault/coursier/blob/d2984cc51bf9b9dacf250717b92983680c03d2a7/project/plugins.sbt#L9) and seems not to need this.

**Comment by fommil** [comment]
yeah, it's really weird. I don't need to do that in my other projects. Some weird setting magic.
