### ISSUE TITLE
cannot resolve codehaus.woodstox

### ISSUE THREAD

**Issue by eikek** [alexarchambault/coursier#246]
Hi,

In our project I got the following error when using coursier:

    [error] 1 error(s):
    [error]   org.codehaus.woodstox:woodstox-core-asl:${woodstox_version}:
    [error]     /home/eike/.sbt/0.13/plugins/target/resolution-cache/org.codehaus.woodstox/woodstox-core-asl/${woodstox_version}/resolved.xml.xml
    [error]     Not found
    [error]     /home/eike/.ivy2/local/org.codehaus.woodstox/woodstox-core-asl/${woodstox_version}/ivys/ivy.xml
    [error]     https://repo1.maven.org/maven2/org/codehaus/woodstox/woodstox-core-asl/$%7Bwoodstox_version%7D/woodstox-core-asl-$%7Bwoodstox_version%7D.pom
    [error]     http://repo.typesafe.com/typesafe/releases/org/codehaus/woodstox/woodstox-core-asl/$%7Bwoodstox_version%7D/woodstox-core-asl-$%7Bwoodstox_version%7D.pom
    [error]     http://maven.aspose.com/repository/ext-release-local/org/codehaus/woodstox/woodstox-core-asl/$%7Bwoodstox_version%7D/woodstox-core-asl-$%7Bwoodstox_version%7D.pom
    [trace] Stack trace suppressed: run last frontend/*:update for the full output.
    

I think its strange that it looks in `.ivy2/local` and not `.ivy2/cache`, no?  We have a sbt project with 3 subproject, where one of them is a play app. We use sbt 0.13.11. Unfortunately, I cannot share the complete sbt config… When I disable the coursier plugin (and remove org.codehaus.* from ivy cache) it works:

    [info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar ...
    [info]  [SUCCESSFUL ] org.codehaus.plexus#plexus-utils;1.5.6!plexus-utils.jar (84ms)
    [info] downloading https://repo1.maven.org/maven2/org/codehaus/woodstox/woodstox-core-asl/4.4.0/woodstox-core-asl-4.4.0.jar ...
    [info]  [SUCCESSFUL ] org.codehaus.woodstox#woodstox-core-asl;4.4.0!woodstox-core-asl.jar (70ms)
    [info] downloading https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar ...

It turns out that the woodstox-asl dependency is pulled in by fhir. A build.sbt with following content reproduces the issue:

    libraryDependencies ++= Seq(
      "ca.uhn.hapi.fhir" % "hapi-fhir-base" % "0.8"
    )
    
This is an very old version, the issue doesn't arise when using fhir 1.5. 

Thanks and regards
Eike

**Comment by eikek** [comment]
This was fast, thank you!

**Comment by alexarchambault** [comment]
Yeah, that was a trivial bug. (The regex matching Maven properties names only accepting a restricted set of characters, which it shouldn't have done...)
