### ISSUE TITLE
launch command: pass flags to main class

### ISSUE THREAD

**Issue by olafurpg** [alexarchambault/coursier#248]
Is there a way to pass flags to the --main class that's started with the `launch` command? Example use case:

```scala
coursier launch com.geirsson:scalafmt-cli_2.11:0.2.3 --main org.scalafmt.cli.Cli  --flags "--file Foo.scala -i"
```

This would start the `org.scalafmt.cli.Cli` main with args `--file Foo.scala -i`.  I couldn't find any examples in the docs. I imagine this could be a simple way for linux/windows users to install scalafmt. It feels cleaner than my current "download scalafmt.jar" solution.

**Comment by alexarchambault** [comment]
This:
```
coursier launch com.geirsson:scalafmt-cli_2.11:0.2.3 --main org.scalafmt.cli.Cli  -- --file Foo.scala -i
```
should work :-)

**Comment by olafurpg** [comment]
I had tried, it doesn't seem to work on in either bash or zsh on my OSX machine

```
$ coursier launch com.geirsson:scalafmt-cli_2.11:0.2.3 --main org.scalafmt.cli.Cli  -- --file Foo.scala -i
Cannot parse dependencies:
  Malformed coordinates: --file
  Malformed coordinates: Foo.scala
  Malformed coordinates: -i
```

**Comment by alexarchambault** [comment]
Maybe you need to update your coursier launcher then (what does `coursier --help` says? this exact syntax should work since 1.0.0-M11 IIRC. `-- --` should work for previous versions though).

Note that you can drop the `--main` argument here, as the main artifact seems to have a `Main-Class` in its manifest, like
```
./coursier launch com.geirsson:scalafmt-cli_2.11:0.2.3 -- --file Foo.scala -i
```

**Comment by olafurpg** [comment]
My bad, I was using 1.0.0-M10. It does work on 1.0.0-M11-1. Excellent, thank you for the prompt response! :)
