### ISSUE TITLE
Pass parameters to jar being launched

### ISSUE THREAD

**Issue by RomanIakovlev** [alexarchambault/coursier#251]
I fancy idea of using coursier to run standalone artifacts without downloading them manually. However I need to pass arguments to those artifacts when running. For example, Wiremock is usually launched like this:

    java -jar wiremock-1.57-standalone.jar --proxy-all="http://search.twitter.com" --record-mappings --verbose

but when I try 

    coursier launch com.github.tomakehurst:wiremock:1.57  --proxy-all="http://search.twitter.com" --record-mappings --verbose

I just get the "unrecognized argument: --proxy-all="http://search.twitter.com"" error, which sort of makes sense. Is it somehow possible to do this?

**Comment by alexarchambault** [comment]
The following:
```
coursier launch com.github.tomakehurst:wiremock:1.57 -- --proxy-all="http://search.twitter.com" --record-mappings --verbose
```
works (a `--` was inserted before the launched app arguments).

I'll make that more clear in the README as soon as I'll update it.

**Comment by RomanIakovlev** [comment]
Thanks, it works!
