### ISSUE TITLE
coursierDependencyTree triggers downloading of JARs

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#253]
It should only trigger downloading of the artifacts (via `coursierResolution`).

**Comment by crypticmind** [comment]
Also, it should not fail in missing dependencies but report them. I have a missing transitive dependency and I cannot find out which module is pulling it.

**Comment by alexarchambault** [comment]
Fixed since `1.0.0-M14` at least.

@crypticmind I agree, that's https://github.com/alexarchambault/coursier/issues/295.
