### ISSUE TITLE
Coursier confuses artifact name and version

### ISSUE THREAD

**Issue by crypticmind** [alexarchambault/coursier#272]
(Note, this could be a possible duplicate of #260)

Given the dep `"net.java.dev.jna" % "jna-platform" % "4.2.2"`
Coursier should fetch `https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.jar`
But instead it tries to fetch `https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.2.2/jna-4.2.2-platform.jar`

**Comment by crypticmind** [comment]
This issue could also be the cause of #263

**Comment by alexarchambault** [comment]
@crypticmind I can't reproduce that. In particular,
```
$ coursier fetch net.java.dev.jna:jna-platform:4.2.2
```
is fine, and fetches both
```
https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar
https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.jar
```
(that is the artifact of `net.java.dev.jna:jna-platform:4.2.2` and of its only transitive dependency).

I'm getting the same results though the SBT plugin.

Do you have a small repro of the problem you're facing (`coursier`-based command or small SBT project)?

**Comment by crypticmind** [comment]
I can't share the project where this originated, but I'll try to craft a new one from it to reproduce the problem.

**Comment by crypticmind** [comment]
I'm attaching a minimal project reproducing this problem.
This is using coursier version 1.0.0-M12

[coursier-272.tar.gz](https://github.com/alexarchambault/coursier/files/324022/coursier-272.tar.gz)

**Comment by alexarchambault** [comment]
The issue originates from `org.mariadb.jdbc:mariadb-java-client:1.1.7` pulling `net.java.dev.jna:jna:3.3.0` with classifier `platform` on the one hand, and `org.scalatestplus:play_2.10:1.2.0` bumping the version of `net.java.dev.jna:jna` to `3.4.0`, for which the artifact with classifier `platform` isn't available any more. This can be reproduced with
```
$ coursier fetch -r https://repo.typesafe.com/typesafe/releases \
    org.scalatestplus:play_2.10:1.2.0 \
    org.mariadb.jdbc:mariadb-java-client:1.1.7
  Error:
https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.4.0/jna-3.4.0-platform.jar: NotFound(https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.4.0/jna-3.4.0-platform.jar,Some(true))
```

Bumping the version of `org.mariadb.jdbc:mariadb-java-client` to `1.3.7` fixes it.

I'm not sure this is actually a bug... The origin of the error could possibly be made clearer by the output, somehow.

**Comment by crypticmind** [comment]
The thing is, you feed this to the stock SBT resolver and it works. What does the stock resolver decide to do in this case?
