### ISSUE TITLE
Add an option to choose a maven profile

### ISSUE THREAD

**Issue by darkjh** [alexarchambault/coursier#279]
When launch/fetch/resolve, sometimes we need a specific maven profile to bring extra modules. For example when launching spark job in yarn cluster, we need spark with `yarn` profile.

**Comment by darkjh** [comment]
@alexarchambault I think we could add the profile here, right? https://github.com/alexarchambault/coursier/blob/master/cli/src/main/scala-2.11/coursier/cli/Helper.scala#L281
There seems to be a `profileActivation` in the `Resolution` object.

**Comment by alexarchambault** [comment]
@darkjh Yeah, `Resolution` can optionally be passed a non-empty `profileActivation: Option[(String, Activation, Map[String, String]) => Boolean]`. The passed method return value says whether the profile it is passed as argument (the `String` arg being the profile ID, the second arg some "activation" info, the third arg the known Maven properties when profiles are checked).

I haven't thought much about what would be the better way of playing with that from the command line and the SBT plugin. If you feel like giving it a try, go for it!

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/issues/293.
