### ISSUE TITLE
Error Resolving Dependency

### ISSUE THREAD

**Issue by darkfrog26** [alexarchambault/coursier#280]
I am trying to use "org.eclipse.jetty" % "jetty-runner" % "9.4.0.M0" programmatically in my project, and if it's already been cached in Ivy then everything works fine, but on a machine that hasn't already cached it, it gives me errors saying it can't find "asm-tree". It says "not found: http://repo1.maven.org/maven2/org/ow2/asm/asm-tree//asm-tree-.pom".  Notice that the version is left off entirely.  I haven't dug through the dependency graph, but it would appear that something is confusing Coursier as it is trying to resolve the dependency.

**Comment by darkfrog26** [comment]
@alexarchambault FYI, I'm using version 1.0.0-M12-1.  If I need to switch to the latest in GitHub let me know.

**Comment by alexarchambault** [comment]
The command
```
coursier fetch org.eclipse.jetty:jetty-runner:9.4.0.M0
```
seems to work fine, both with a filled and an empty cache (by having `COURSIER_CACHE` point to an initially empty directory).

I can't investigate right now what the problem can be from the API, but that should be an easy fix as it works from the command line.

**Comment by darkfrog26** [comment]
If I ignore `Resolution.errors` everything seems to work okay.  Is the command-line tool ignoring errors coming back?

Here's my code:

```scala
      val start = Resolution(Set(Dependency(Module(vd.group, vd.name), vd.version.toString())))
      val fetch = Fetch.from(repositories, Cache.fetch())
      val resolution = start.process.run(fetch).run
      val errors = resolution.errors
      val conflicts = resolution.conflicts

      if (errors.nonEmpty) {
        throw new RuntimeException(s"Errors for ($vd): $errors")
      }
```

**Comment by alexarchambault** [comment]
The following seems to be working (coursier 1.0.0-M12-1 too):
```scala
import coursier._

val repositories = Seq(MavenRepository("https://repo1.maven.org/maven2"))
val start = Resolution(Set(Dependency(Module("org.eclipse.jetty", "jetty-runner"), "9.4.0.M0")))
val fetch = Fetch.from(repositories, Cache.fetch())
val resolution = start.process.run(fetch).run
val errors = resolution.errors
val conflicts = resolution.conflicts
```
and doesn't give me any error or conflict.

Are you sure `vd.group`, `vd.name`, and `vd.version` give the right values?

**Comment by alexarchambault** [comment]
Closing this. Re-open with more details if you still face a problem.
