### ISSUE TITLE
Cannot resolve sbt interface from "org.scala-sbt"

### ISSUE THREAD

**Issue by felixmulder** [alexarchambault/coursier#284]
In our build file coursier cannot resolve the sbt interface from `org.scala-sbt`, but it can from `com.typesafe.sbt`.

```scala
// ...
"org.scala-sbt" % "interface" % "0.13.11" // doesn't work
"com.typesafe.sbt" % "sbt-interface" % "0.13.11" // works
```

For us it should make little difference using one or the other, but thought I'd report it anyway.

Let me know what logs etc I should dig up.

**Comment by alexarchambault** [comment]
I guess that originates from the latter being available on Central, where as the former is only available from the Typesafe ivy-releases repo. Do you have more context? Does the problem only happens with sbt-coursier?

**Comment by felixmulder** [comment]
The problem only occurs with sbt-coursier. This is the build file - https://github.com/lampepfl/dotty/blob/master/project/Build.scala. Since we're using:

```
resolvers += Resolver.typesafeIvyRepo("releases")
```

I figured this would allow coursier to resolve it from the ivy releases.

**Comment by alexarchambault** [comment]
It seems that you're running into the [this point of the FAQ](https://github.com/alexarchambault/coursier#why-does-coursier-seem-not-to-find-some-artifacts-whereas-sbt-does). With the default SBT resolution, one can add the necessary resolvers to one single project as you did, and let it fill the cache for the subsequent projects. On the other hand, coursier doesn't mix the caches of the various repositories. The resolvers have to be added to all the projects that need artifacts from them.

So here, the `dotty` project and the projects that depend on it need the typesafe ivy repo too. It works by enforcing that like shown here: https://github.com/alexarchambault/dotty/commit/86111cf2557dac7f5ee61de65c60a2db2555d87f.

**Comment by felixmulder** [comment]
Great, thanks :)
