### ISSUE TITLE
Credential issue with ProjectRef

### ISSUE THREAD

**Issue by mathieuleclaire** [alexarchambault/coursier#285]
Hi,
when using ProjectRef, coursier complains about the fact that a credential file is missing.

```sh 
[trace] Stack trace suppressed: run last {https://github.com/Nycto/Hasher.git#v1.2.0}hasher/*:coursierResolution for the full output.
[error] ({https://github.com/Nycto/Hasher.git#v1.2.0}hasher/*:coursierResolution) Credentials file /home/mathieu/.ivy2/.credentials does not exist
```

For instance:

```scala
lazy val hasher =
    ProjectRef(uri("https://github.com/Nycto/Hasher.git#v1.2.0"), "hasher")
```

where hasher is used by an other project:
```scala
lazy val other = Project(...) dependsOn(hasher)
```

**Comment by alexarchambault** [comment]
Have you tried with sbt-coursier `1.0.0-M12`? (I'm assuming you're using `1.0.0-M12-1`, with which I ran into this issue too.) `1.0.0-M12-1` [doesn't bring much](https://github.com/alexarchambault/coursier/blob/master/notes/1.0.0-M12-1.markdown) if you're not using crendentials.

In 1.0.0-M13, `credentials` won't be checked by default, that should fix that.

**Comment by mathieuleclaire** [comment]
It works with M12, the M13 were not deployed yet. 
Thanks !
