### ISSUE TITLE
Coursier evicting the wrong versions

### ISSUE THREAD

**Issue by newhoggy** [alexarchambault/coursier#291]
With coursier:

![image](https://cloud.githubusercontent.com/assets/63014/16473098/9f01564e-3ead-11e6-91fd-ae0f92bb8130.png)

Without coursier:
![image](https://cloud.githubusercontent.com/assets/63014/16472948/67af0d36-3eac-11e6-83a4-40881613a3a6.png)

`sbt dependency-graph` always shows the correct eviction regardless of whether coursier is installed.

```
10:15 $ sbt dependency-graph | grep evicted | sed 's/.*+-//g' | sort | uniq
com.101tec:zkclient:0.5 (evicted by: 0.7)
com.fasterxml.jackson.core:jackson-databind:2.5.4 (evicted by: 2.6.6)
commons-logging:commons-logging:1.2 (evicted by: 1.1.3)
log4j:log4j:1.2.15 (evicted by: 1.2.17)
log4j:log4j:1.2.16 (evicted by: 1.2.17)
net.arbor:config-core_2.11:2.0.0-4 (evicted by: 2.1.0-10)
net.arbor:config-core_2.11:2.0.2-8 (evicted by: 2.1.0-10)
net.arbor:scalaz-core_2.11:3.0.1-146 (evicted by: 3.0.2-158)
org.apache.avro:avro:1.7.7 (evicted by: 1.8.0)
org.apache.zookeeper:zookeeper:3.4.3 (evicted by: 3.4.6)
org.slf4j:slf4j-api:1.6.1 (evicted by: 1.7.7)
org.slf4j:slf4j-api:1.7.2 (evicted by: 1.7.7)
org.slf4j:slf4j-api:1.7.6 (evicted by: 1.7.7)
org.slf4j:slf4j-log4j12:1.6.1 (evicted by: 1.7.6)
org.xerial.snappy:snappy-java:1.1.1.3 (evicted by: 1.1.1.7)
```

I don't know why Coursier would choose `2.0.0-4` over `2.1.0-10`.

Initially, I though it was the commit count `-4` being lexicographically higher than `-10`, but this is the minor version number `1` is higher than `0`, so that should have taken precedence anyway.

**Comment by newhoggy** [comment]
Also it is worrying that `dependency-graph` doesn't have visibility over what coursier is doing, which means that we will have difficulty debugging dependency issues when coursier is enabled.

**Comment by alexarchambault** [comment]
coursier should handle version ordering as expected (so `2.0.0-4` < `2.0.0-10`).

It has a (not too documented yet) `coursierDependencyTree` to print sbt-dependency-graph like trees. It could help to know what's happening here.

About sbt-dependency-graph, it relies more directly on Ivy, and ignores the keys sbt-coursier overrides. It seems a hassle to adapt to coursier, that's why I started adding similar features directly into sbt-coursier.

**Comment by alexarchambault** [comment]
Closing this. Re-open if you have more details.
