### ISSUE TITLE
Having a word at the end of the version errors out

### ISSUE THREAD

**Issue by vito-c** [alexarchambault/coursier#297]
For example version `6.1.0.Final` will result in the version being stripped out from the resolver:

`https://repository.jboss.org/nexus/content/repositories/releases/org/drools/drools-reteoo/6.1.0.Final/`

```
[error]   org.drools:drools-reteoo::
[error]     not found: /Users/vito-c/.sbt/0.13/plugins/target/resolution-cache/org.drools/drools-reteoo/resolved.xml.xml
[error]     Not found
[error]     not found: /Users/vito-c/.ivy2/local/org.drools/drools-reteoo/ivys/ivy.xml
[error]     not found: https://repo1.maven.org/maven2/org/drools/drools-reteoo//drools-reteoo-.pom
[error]     not found: https://repository.jboss.org/nexus/content/repositories/releases/org/drools/drools-reteoo//drools-reteoo-.pom
```

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/coursier/pull/293 has some fixes related to dependency management, properties, etc. and happen to fix that too. It will be included in `1.0.0-M13`.

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/coursier/pull/293 fixes
```
coursier resolve org.drools:drools-reteoo:6.1.0.Final
```
at least.

**Comment by vito-c** [comment]
ok cool I'll pull it and give it a try.

**Comment by vito-c** [comment]
it worked :)
