### ISSUE TITLE
Local repository priority

### ISSUE THREAD

**Issue by mathieuleclaire** [alexarchambault/coursier#301]
Is it possible to enforce coursier to give the priority to libraries, which have been published locally rather than the ones from remote repositories ? It is typically convenient when trying to hack some library by means of a fork (with the idea of submitting a PR ).

Thanks

**Comment by alexarchambault** [comment]
It should already be the case by default, both from the CLI tools (via [this code](https://github.com/alexarchambault/coursier/blob/d2340c891e5f709fb2aa2e26539b7ff9efcd7a0a/cli/src/main/scala-2.11/coursier/cli/Helper.scala#L111-L114)) and the SBT plugin (SBT sets up resolvers with `~/.ivy2/local` before the others).

Unless you meant `~/.m2` (Maven local repo)?

**Comment by mathieuleclaire** [comment]
I try to patch a lib published on maven2. I publish in .ivy2/local. The version from the maven2 repo is always chosen. Isn't it because they both (maven2 and .ivy2) belong to the defaultRepositories ? What happens in this case ? It seems that maven2 is taken first.

**Comment by alexarchambault** [comment]
That should be the case by default too.

From SBT, you can check `show coursierResolvers` for that.

**Comment by alexarchambault** [comment]
Closing this. Re-open if you have more details.
