### ISSUE TITLE
`sbt-coursier` artifacts missing from Maven Central

### ISSUE THREAD

**Issue by josh-newman** [alexarchambault/coursier#309]
I tried following the README's setup instructions by adding `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12")` to my project's build.sbt. However, I can't seem to find those artifacts in Maven Central. The .pom and .jar links [for `sbt-coursier` lead to 404s](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22sbt-coursier%22) (while [the `coursier_2.11` ones do work](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22coursier_2.11%22), for example).

When I published coursier locally (with `sbt publishLocal`) resolution worked, suggesting the Maven Central artifacts are wrong, but I'm not too familiar with Maven Central. Am I following the plugin setup instructions incorrectly? Thanks!

**Comment by alexarchambault** [comment]
The `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12")` line should be added to a `.sbt` file under `project/` (it's usually put in `project/plugins.sbt`), not to the `build.sbt` file at the root of the project :-)

**Comment by alexarchambault** [comment]
Closing this. Feel free to re-open if it still doesn't work (or ask on the gitter channel).

**Comment by josh-newman** [comment]
Sorry for the delay. I realized I mis-wrote earlier; I actually did add things to my project/plugins.sbt earlier, as you described.

However, I was previously setting my `externalResolvers` to just `Resolver.sbtPluginRepo("releases")` (editing an older, shared project; I'm not sure why it needed to be configured). When I switched to `DefaultMavenRepository`, it worked.

This is what failed to resolve with `Resolver.sbtPluginRepo("releases")`:
* https://repo.typesafe.com/typesafe/ivy-releases/io.get-coursier/sbt-coursier/scala_2.10/sbt_0.13/1.0.0-M14/ivys/ivy.xml
* https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.get-coursier/sbt-coursier/scala_2.10/sbt_0.13/1.0.0-M14/ivys/ivy.xml

And these successfully resolved with `DefaultMavenRepository`:
* https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M14/sbt-coursier-1.0.0-M14.jar
* https://repo1.maven.org/maven2/io/get-coursier/coursier_2.10/1.0.0-M14/coursier_2.10-1.0.0-M14.jar

I'm not sure why the URLs are a bit different (since I don't know much about Maven/Ivy), but I just wanted to copy that down here in case there's actually a problem and it's helpful to you.

In case it's relevant, I'm still seeing 404s for [the artifact JAR files in Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22sbt-coursier%22):
* https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M14/sbt-coursier-1.0.0-M14.jar
* https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier/1.0.0-M12/sbt-coursier-1.0.0-M12.jar
* https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier/1.0.0-M14-2/sbt-coursier-1.0.0-M14-2.jar

Thanks for your help!
