### ISSUE TITLE
Are Classifiers Ignored in Ivy Files?

### ISSUE THREAD

**Issue by tjni** [alexarchambault/coursier#320]
I am working on using Coursier on a project at work and ran into the following situation. My project depends on a custom configuration called "testArtifacts" of a dependency. The Ivy file looks like:

```
<publications>
  <artifact name="util" type="jar" ext="jar" conf="runtime"/>
  <artifact name="util" type="jar" ext="jar" conf="javadoc" m:classifier="javadoc"/>
  <artifact name="util" type="jar" ext="jar" conf="sources" m:classifier="sources"/>
  <artifact name="util" type="jar" ext="jar" conf="testArtifacts" m:classifier="test"/>
</publications>
```

Possibly as a side effect of 3e9a37edc358e1960ce607e9958c310afa2a01c8 (educated guess), this dependency is not being download as part of the `update` task. Is there a good path forward to supporting this use case?

Disclaimer: I know only enough about Ivy/SBT to scrape by, but I'll try to keep up. 😃

**Comment by tjni** [comment]
I verified that reverting 3e9a37edc358e1960ce607e9958c310afa2a01c8 in a local build based off of 1.0.0-M12 resolves my use case.

But I trust that this change was made for a reason. I'm happy to spend some time coming up with a resolution, but I'll need some help understanding the motivation behind the commit.

**Comment by alexarchambault** [comment]
FYI 1.0.0-M14 should be released in a few hours, fixing the quite similar https://github.com/alexarchambault/coursier/issues/322.

**Comment by alexarchambault** [comment]
@tjni `1.0.0-M14` fixed similar regressions. Feel free to re-open if it doesn't fix that.
