### ISSUE TITLE
Dynamic revision not resolved to latest sub-revision

### ISSUE THREAD

**Issue by avdv** [alexarchambault/coursier#351]
We have revisions like 2.5.8-0 and 2.5.8-1 published to our hosted Artifactory ivy repository.

Trying to resolve the dynamic revision "2.5.+" which should select 2.5.8-1 according to http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html

Using sbt-coursier `"io.get-coursier" % "sbt-coursier" % "1.0.0-M14"` this resolves to 2.5.8-0 whereas with vanilla sbt it indeed resolves to the latest version.

**Comment by alexarchambault** [comment]
It should resolve to `2.5.8-1`... Are you sure the corresponding Maven metadata (like [this one](https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/maven-metadata.xml), if this comes from a Maven repo) reference `2.5.8-1`? If it comes from an Ivy repo, there should be a directory listing in cache (as a hidden file in the directory have version dirs as sub-directories). Beware that there's a TTL of 24 hours by default for both of these. Try set `COURSIER_TTL` to `0s` in the env?

**Comment by mtomko** [comment]
We have also seen some strange behavior with Coursier (also 1.0.0-M14) and wildcard dependencies. I have the following dependency in my build.sbt: `"org.broadinstitute" %% "blzero" % "0.6.+"`

Running `sbt compile`, I get:

```scala
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.broadinstitute:blzero_2.11:0.6.+:
[error]     not found:
[error]       /Users/mtomko/.ivy2/local/org.broadinstitute/blzero_2.11
[error]       https://repo1.maven.org/maven2/org/broadinstitute/blzero_2.11/maven-metadata.xml
[error]       https://oss.sonatype.org/content/repositories/releases/org/broadinstitute/blzero_2.11/maven-metadata.xml
[error]       http://rnaivm3.broadinstitute.org:10080/nexus/content/groups/public/org/broadinstitute/blzero_2.11/maven-metadata.xml
[error] Total time: 2 s, completed Nov 16, 2016 10:47:52 AM
>
```

I can confirm that the `rnaivm3` nexus server has a number of artifacts matching `0.6.+` - specifically, we have revisions `0.6.0` through `0.6.4`.

**Comment by avdv** [comment]
Closing this, as it never turned up again. Indeed, the `.directory` file is there and its contents is up-to-date.
