### ISSUE TITLE
Failure to parse certain (v1,v2] VersionIntervals

### ISSUE THREAD

**Issue by eboto** [alexarchambault/coursier#355]
I haven't fully characterized this, but when trying to parse [the latest amazon kinesis producer pom.xml](https://repo1.maven.org/maven2/com/amazonaws/amazon-kinesis-producer/0.12.0/amazon-kinesis-producer-0.12.0.pom) coursier produced many outputs of the following format:

`Ignoring unparsed versions: Vector((1.11.0, 1.12.0])`

However, I believe that the string is a well-formed maven dependency interval string.

After digging in, I believe the code in question is [Parse.versionInterval](https://github.com/alexarchambault/coursier/blob/f61a25857460758d7c2e1eb56e526f309ad00993/core/shared/src/main/scala/coursier/core/Parse.scala#L31-L50) and I have made [a test case to reproduce it](https://github.com/alexarchambault/coursier/pull/354).

Posting this issue here in case there's some context I'm missing, but I will continue characterizing the problem.

**Comment by eboto** [comment]
OK I have narrowed it down to `Parse.version`. The problem is that the versions interval in the `pom.xml` contains a space after the comma, and coursier is not yet robust to that. I have added a `trim` call to the PR, which should fix the broken test that demonstrated the error.

**Comment by eboto** [comment]
@alexarchambault  any questions or concerns about this change?

**Comment by eboto** [comment]
Closing due to merge of #354

**Comment by alexarchambault** [comment]
@eboto Thanks again for having investigated (and fixed :-) that!
