### ISSUE TITLE
Local Maven Repository Support (.m2)?

### ISSUE THREAD

**Issue by darkfrog26** [alexarchambault/coursier#361]
I'm attempting to publish a private dependency to a remote server and then use via Coursier but this isn't working because apparently SBT doesn't publish `ivys/ivy.xml` which Coursier needs (see http://stackoverflow.com/questions/40095817/how-do-i-publish-an-ivy-dependency-via-sbt).

If I change to publish as a Maven dependency can I configure Coursier to look at my local Maven repository (.m2) in addition to my local Ivy repository (.ivy2)?  Looking at the API there does not seem to be a straight-forward way to do this (like in Cache.ivy2Local / ivy2Cache).

**Comment by darkfrog26** [comment]
This is a less pressing issue now as my StackOverflow question was answered, but this would be a nice feature to have convenient access to local maven.

**Comment by alexarchambault** [comment]
Adding `resolvers += Resolver.mavenLocal` in `build.sbt` should work (that adds `~/.m2/local` as a repository - I haven't tried though).

**Comment by tyrcho** [comment]
works for me, thanks @alexarchambault

**Comment by scottcarey** [comment]
I've been blocked by this several times.

I need to launch something that has no build.sbt, that exists in a local maven repo, or a dependency iis n the local maven repo that is otherwise unavailable due to network conditions.
