### ISSUE TITLE
 coursierUseSbtCredentials in Global := true has no effect in a multi-project

### ISSUE THREAD

**Issue by evacchi** [alexarchambault/coursier#371]
I have tried setting in my gitignored `local.sbt` the setting `coursierUseSbtCredentials := true in Global` so that it could be applied to all my subprojects, but it does not have any effect. It requires a bit more work:

http://stackoverflow.com/questions/40283814/setting-a-key-local-sbt-so-that-it-is-applied-in-a-multi-project/40283960#40283960

Is there a reason for this choice ?

**Comment by alexarchambault** [comment]
Closing this to keep the discussion under https://github.com/alexarchambault/coursier/issues/358.
