### ISSUE TITLE
Maven dependency management with a POM only parent and SNAPSHOT

### ISSUE THREAD

**Issue by chikei** [alexarchambault/coursier#380]
So if I try to fetch a maven artifact using maven dependency management and if the parent is a POM only project, coursier will try to fetch SNAPSHOT instead of the timestamped snapshot version.

I have located the code cause the problem [MavenRepository](https://github.com/alexarchambault/coursier/blob/master/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L221) where for pom only project versioningOption will resolve to `None`, there is a naive solution that adding one more `orElse` to check against `pom` extension, but I am not familiar with the code enough to tell if this change will cause any regression.

**Comment by alexarchambault** [comment]
This should be the same as https://github.com/alexarchambault/coursier/issues/169. Keeping the discussion there.

**Comment by mandrean** [comment]
For anyone coming here from Google, the URL to the above issue is now #169
