### ISSUE TITLE
Cache directory structure when using credentials

### ISSUE THREAD

**Issue by tomaszf** [alexarchambault/coursier#382]
Hi,

I noticed that when using credentials to access repository, fetched artifacts are saved to the directory `.coursier/cache/v1/https/USERNAME%40REPOSITORY_HOSTNAME`

Is there a rationale behind creating separate directories for the same **REPOSITORY_HOSTNAME** but different **USERNAME**?

**Comment by alexarchambault** [comment]
Yep, the rationale is not to mix up things fetched while authenticated with those fetched while not authenticated.

**Comment by tomaszf** [comment]
Ok, thx for reply!

**Comment by wpc009** [comment]
I'm facing a really annoying problem caused by this issue.
The `%40` in the path will cause escaping when transfers to URI and then to URL instance. Which is used quite a lot in `Spark`.  `%40` will be escaped to `%2540` which does not exists.
