### ISSUE TITLE
java 6 support

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#390]
I know we said we're moving to JDK 8 but if we do all the resolving in the sbt-ensime sbt plugin instead of the clients, we do all the resolving work in one place and remove a bunch of client code. Hence I created https://github.com/ensime/ensime-sbt/issues/260

However, since the sbt plugin has to run on JDK6 (which allows JDK6 projects to be supported by running ensime on JDK8) it means we'll need coursier Java 6 support and I think you might have dropped it.

What all needs to be done to bring the java6 branch up to speed with the mainline?

**Comment by alexarchambault** [comment]
Sorry, I forgot a bit about the Java 6 branch, all the more that ensime seemed to have switched to Java 8.

I usually bring it up-to-date by looking at the merge commits in master (`git log master ^topic/java-6 --merges`). I then do a git merge to these from the java 6 branch, in chronological order, adjusting what needs to be adjusted along the way (by checking `sbt testsJVM/test` from Java 6).

**Comment by alexarchambault** [comment]
Fixed by `1.0.0-M15`.

**Comment by fommil** [comment]
you are my hero!
