### ISSUE TITLE
change artifact/version convention for java 6 jars

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#397]
I'm looking into depending on the java6 version of coursier in ensime-sbt.

But a problem is that if the user depends on coursier-sbt, it will pull in a different version of coursier and then the version that is actually used will depend on whatever comes first in the classpath.

Rather than change the artifact name, could you perhaps publish the java6 version with a different version string? e.g. `1.0.0-M12-java6`, which allows one of them to win.

**Comment by alexarchambault** [comment]
I might revise my plans for 1.0 (as briefly discussed on Twitter), that is release it earlier, and have it target java 6 (as [you suggested](https://twitter.com/fommil/status/800613052454473728)).

**Comment by fommil** [comment]
that would be so good, I owe you all the beers at Scala Sphere :smile:

**Comment by fommil** [comment]
it's been a long time coming, but I'm hoping that by this weekend I'll have sbt-ensime using coursier to install/deploy the ensime-server (instead of the clients).

**Comment by alexarchambault** [comment]
@fommil `1.0.0-M15`, which should support Java 6, was just released. Switching to it should fix https://github.com/ensime/ensime-sbt/issues/275 and https://github.com/ensime/ensime-sbt/issues/277.
