### ISSUE TITLE
NoSuchMethod error on coursier.package$Resolution$.apply(...)

### ISSUE THREAD

**Issue by chipsenkbeil** [alexarchambault/coursier#417]
I've suddenly been bit by this on multiple projects over the past month. Any idea what the problem might be? Leftover binaries? Conflicting Coursier plugin versions (between project and global installations)?

```
[error] (scalaDebuggerDocs/*:coursierResolution) java.lang.NoSuchMethodError: coursier.package$Resolution$.apply(Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;)Lcoursier/core/Resolution;
```

**Comment by alexarchambault** [comment]
I've been getting some of those when the sbt-coursier version was conflicting with the one from sbt-ensime... Ensuring everything pulls the same coursier version solved the issue.

**Comment by chipsenkbeil** [comment]
Yep, that was it. My project had one version of Coursier while `sbt-ensime` was bringing in another.
