### ISSUE TITLE
Update version string in the README to point to the 1.0.0-M15-1 release instead of the M15 one

### ISSUE THREAD

**Issue by philippw** [alexarchambault/coursier#427]
The one -1 release is the one listed in Maven Central. The README still uses the M15 release (which cannot be resolved), which necessitates some investigation.

Please fix it.
Thanks.

**Comment by philippw** [comment]
@alexarchambault please update the version string from:
`addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")`
to:
`addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15-1")`

People are running into problems due to this tiny error. E.g. #425

**Comment by alexarchambault** [comment]
The `1.0.0-M??-?` releases are not meant for a wide use. These should be used only if you know what you're doing (like you're interested in a recently fixed bug). The README only advertises the `1.0.0-M??` versions.
