### ISSUE TITLE
SBT integration

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#52]
Several points to answer / know more about:
- would a SBT plugin be enough to have SBT use coursier instead of Ivy?
- according to @jsuereth, generating an `UpdateReport` is needed at least (https://twitter.com/jsuereth/status/611983195324719104, https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/UpdateReport.scala#L189),
- along with support for Ivy-like configurations (https://twitter.com/jsuereth/status/611982250121543680).
- take into account dependencies between sub-projects,
- ...

**Comment by fommil** [comment]
I'd really love to be able to use a without-ivy sbt. Very excited about this ticket.

BTW, it seems that ivy is used internally even if there are no ivy dependencies :-( I really wish sbt would be refactored to remove this constraint https://github.com/sbt/sbt/issues/2266

As a quick hack, you might want to look at create `unmanagedJars` (which won't appear in the output `pom.xml`) and doing something similar to ensime for the classifiers https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala#L55

**Comment by alexarchambault** [comment]
There's already a basic plugin on the [topic/sbt-plugin branch](https://github.com/alexarchambault/coursier/tree/topic/sbt-plugin), but Ivy configuration have to be handled for this to really work (see [this branch](https://github.com/alexarchambault/coursier/tree/topic/configurations) for that).

For now, it fetches things, but SBT can't find the right configurations in the generated report, the `scala-tools` one in particular.

**Comment by fommil** [comment]
I'm going to be looking into the guts of the `UpdateReports` tonight/tomorrow for other reasons ... https://github.com/ensime/ensime-sbt/issues/117 oh what joy

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/pull/92.
