### ISSUE TITLE
add a gitter badge

### ISSUE THREAD

**Issue by antonkulaga** [alexarchambault/coursier#57]
It would be nice to have a gitter chat on this lib.

P.S. (Offtopic): ivy is terrible and sbt spends a lot of time on dependency resolution with it, is there any sbt plugin in plans that will switch all resolution from ivy to coursier without chaning anything in build configuration?

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/commit/316b4d1dacbc62ff863f32fa3be4cd94be0e5e23.
