### ISSUE TITLE
Better conscript

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#7]
It should be possible to have an equivalent of [conscript](https://github.com/n8han/conscript), to launch artifact based apps. With a better cache, and faster startup times and updates.

One thing to tackle would be the dependency on org.scala-sbt:launcher-interface that these artifacts have. (Only its last version seems to be on Maven Central.)

Some need to get things from Ivy repositories too.

**Comment by alexarchambault** [comment]
Needs https://github.com/alexarchambault/coursier/issues/8.

**Comment by nafg** [comment]
#8 is done. It seems from the readme that this is implemented too?

**Comment by alexarchambault** [comment]
@nafg There's a launcher now. So, yeah, I'm going to close this one... Although it's now able to launch conscript apps as is (the way conscript does, from a Github repo).
