### ISSUE TITLE
Ivy repositories support

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#8]
But for Ivy "configurations", which are a generalization of Maven scopes, the Ivy model seems easier and less error prone / ambiguous than the Maven one. In particular, there's no inheritance, no dependency management, supposedly no property substitution needed for published artifacts, ...

**Comment by alexarchambault** [comment]
See the points discussed here: https://gitter.im/lihaoyi/Ammonite/archives/2015/06/17

Exclusions are a bit more complex (more matched fields, regexes).

**Comment by alexarchambault** [comment]
Features that need to be added for that:
- [ ] replace Maven scopes (hard-coded compile/runtime/test/...) by Ivy-like configurations, some configuration map is likely to be added to `Project`, and a default Maven one defined in `Resolution`,
- [ ] create an implementation of `Remote` (repository) for Ivy repositories, requiring the next point,
- [ ] parse Ivy repositories patterns (*examples*),
- [ ] in `Project` definition, change the type of `dependencies: Seq[Dependency]` to `Seq[(String, Dependency)]`, where `String` would stand for the configuration of `Project` this dependency is added to,
- [ ] add support for Ivy more refined exclusions (pattern matching, ...),
- [ ] add some support for specified before hand conflict resolution.

Possibly not exhaustive, and hopefully not hiding or implying any show stopper or too complex issues.

**Comment by alexarchambault** [comment]
Needs https://github.com/alexarchambault/coursier/issues/83.

**Comment by fommil** [comment]
in particular the ivy local directory

**Comment by alexarchambault** [comment]
You mean `~/.ivy2/cache`? `~/.ivy2/local` is already supported, thanks to the Maven POMs that SBT puts in it.

**Comment by fommil** [comment]
Yes, the ivy cache.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/pull/92.
