### ISSUE TITLE
windows-compatible launcher

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#89]
I just had a look inside the `coursier` launcher and seen that it is a script file. Any chance of having a version which is a `jar` file?

I'd be very happy with a proguard version with all bootstrapped jars bundled.

**Comment by alexarchambault** [comment]
Yeah, just a JAR (no shell) could be done. All the parameters added in the script would be added in a config file, put in the JAR, then read by it when it is run. I'll have a look.

**Comment by alexarchambault** [comment]
Yeah, just a JAR (no shell) could be done. All the parameters added in the script would be added in a config file, put in the JAR, then read by it when it is run. I'll have a look.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/coursier/commit/3ead95b324225320e948bf5b5bdbc245aa3fcc30.

**Comment by alexarchambault** [comment]
Would need integration tests though...
